# Generated by Django 4.1.3 on 2022-12-19 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OSINTS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_id', models.CharField(max_length=24)),
                ('company_name', models.CharField(max_length=32)),
                ('target', models.CharField(max_length=64)),
                ('scan_name', models.CharField(max_length=32)),
                ('scan_date', models.DateField(auto_now_add=True)),
                ('file_name', models.CharField(blank=True, max_length=1024)),
                ('completed', models.BooleanField(default=False)),
                ('msp_id', models.CharField(default='msp_id', max_length=32)),
            ],
        ),
    ]
