# Generated by Django 4.1.3 on 2023-01-06 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OSINT', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='osints',
            name='scan_type',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
