# Generated by Django 4.0.4 on 2022-05-02 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MSP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msp_name', models.CharField(max_length=100)),
                ('msp_logo', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('contact_email', models.CharField(max_length=50)),
                ('contact_first_name', models.CharField(max_length=50)),
                ('contact_last_name', models.CharField(max_length=50)),
            ],
        ),
    ]
