# Generated by Django 4.0.4 on 2022-05-04 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(max_length=50)),
                ('email_1', models.EmailField(max_length=100)),
                ('email_2', models.EmailField(max_length=100)),
                ('email_3', models.EmailField(max_length=100)),
                ('email_4', models.EmailField(max_length=100)),
                ('email_5', models.EmailField(max_length=100)),
                ('email_6', models.EmailField(max_length=100)),
                ('email_7', models.EmailField(max_length=100)),
                ('email_8', models.EmailField(max_length=100)),
                ('email_9', models.EmailField(max_length=100)),
                ('email_10', models.EmailField(max_length=100)),
                ('email_11', models.EmailField(max_length=100)),
                ('email_12', models.EmailField(max_length=100)),
                ('email_13', models.EmailField(max_length=100)),
                ('email_14', models.EmailField(max_length=100)),
                ('email_15', models.EmailField(max_length=100)),
                ('email_16', models.EmailField(max_length=100)),
                ('email_17', models.EmailField(max_length=100)),
                ('email_18', models.EmailField(max_length=100)),
                ('email_19', models.EmailField(max_length=100)),
                ('email_20', models.EmailField(max_length=100)),
                ('email_21', models.EmailField(max_length=100)),
                ('email_22', models.EmailField(max_length=100)),
                ('email_23', models.EmailField(max_length=100)),
                ('email_24', models.EmailField(max_length=100)),
                ('email_25', models.EmailField(max_length=100)),
                ('email_26', models.EmailField(max_length=100)),
                ('email_27', models.EmailField(max_length=100)),
                ('email_28', models.EmailField(max_length=100)),
                ('email_29', models.EmailField(max_length=100)),
                ('email_30', models.EmailField(max_length=100)),
            ],
        ),
    ]
