# Generated by Django 4.1.3 on 2022-11-30 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msp_id', models.CharField(max_length=32)),
                ('company_name', models.CharField(max_length=32)),
                ('public_ip', models.CharField(max_length=15, null=True)),
                ('company_domain', models.CharField(max_length=64, null=True)),
                ('primary_mail_domain', models.CharField(max_length=32)),
                ('is_verified', models.BooleanField(default=False)),
                ('company_id', models.CharField(max_length=10, null=True)),
            ],
        ),
    ]
