# Generated by Django 4.0.4 on 2022-05-02 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('msps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('website_url', models.CharField(max_length=75)),
                ('external_ip', models.CharField(max_length=15)),
                ('company_logo', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('msp', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='msps.msp')),
            ],
        ),
    ]
