# Generated by Django 4.0.4 on 2022-05-02 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('msps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emailtemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_teplate', models.TextField()),
                ('msp_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='msps.msp')),
            ],
        ),
    ]
