# Generated by Django 4.1.3 on 2022-11-21 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phishing', '0002_campaings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Campaings',
            new_name='Campaigns',
        ),
        migrations.RenameField(
            model_name='campaigns',
            old_name='campagin_name',
            new_name='campaign_ID',
        ),
        migrations.RenameField(
            model_name='campaigns',
            old_name='campaing_ID',
            new_name='campaign_name',
        ),
    ]
