# Generated by Django 4.1.3 on 2022-11-21 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phishing', '0004_campaigns_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaigns',
            old_name='campaign_ID',
            new_name='campaign_id',
        ),
    ]
