# Generated by Django 4.1.3 on 2022-11-23 15:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('phishing', '0005_rename_campaign_id_campaigns_campaign_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracking',
            name='campaign_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tracking',
            name='campaign_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=32),
            preserve_default=False,
        ),
    ]
