# Generated by Django 4.1.3 on 2022-11-23 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phishing', '0006_tracking_campaign_id_tracking_campaign_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msp_id', models.CharField(max_length=32)),
                ('company_name', models.CharField(max_length=32)),
                ('campaign_name', models.CharField(max_length=32)),
                ('campaign_id', models.CharField(max_length=32)),
                ('tracking_id', models.CharField(max_length=16)),
                ('email_clicked', models.BooleanField(default=False)),
                ('email_clicked_time', models.TimeField()),
                ('link_clicked', models.BooleanField(default=False)),
                ('link_clicked_time', models.TimeField()),
                ('target_email', models.CharField(max_length=128)),
            ],
        ),
        migrations.DeleteModel(
            name='Tracking',
        ),
    ]
