# Generated by Django 4.1.3 on 2022-12-02 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phishing', '0009_emailtracking_template_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaigns',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
