# Generated by Django 4.1.3 on 2022-12-06 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wpscan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scans',
            name='file_name',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
