# Generated by Django 4.1.3 on 2022-12-06 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wpscan', '0002_scans_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='scans',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
