# Generated by Django 4.1.3 on 2022-12-06 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wpscan', '0003_scans_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='scans',
            name='msp_id',
            field=models.CharField(default='msp_id', max_length=32),
        ),
    ]
