# Generated by Django 4.1.3 on 2022-12-07 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wpscan', '0004_scans_msp_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scans',
            name='scan_id',
            field=models.CharField(max_length=24),
        ),
    ]
