# Generated by Django 4.1.3 on 2022-12-07 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wpscan', '0005_alter_scans_scan_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scans',
            name='file_name',
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
