# Generated by Django 4.1.3 on 2022-12-12 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wpscan', '0006_alter_scans_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='scans',
            name='data',
            field=models.CharField(blank=True, max_length=100000),
        ),
    ]
