# Generated by Django 4.1.3 on 2022-12-12 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wpscan', '0007_scans_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scans',
            name='data',
        ),
        migrations.AddField(
            model_name='scans',
            name='alerts',
            field=models.CharField(blank=True, max_length=1400),
        ),
        migrations.AddField(
            model_name='scans',
            name='errors',
            field=models.CharField(blank=True, max_length=1400),
        ),
        migrations.AddField(
            model_name='scans',
            name='finds',
            field=models.CharField(blank=True, max_length=1400),
        ),
        migrations.AddField(
            model_name='scans',
            name='info',
            field=models.CharField(blank=True, max_length=1400),
        ),
        migrations.AddField(
            model_name='scans',
            name='resu',
            field=models.CharField(blank=True, max_length=1400),
        ),
        migrations.AddField(
            model_name='scans',
            name='sum',
            field=models.CharField(blank=True, max_length=1400),
        ),
        migrations.AddField(
            model_name='scans',
            name='sum_line',
            field=models.CharField(blank=True, max_length=1400),
        ),
        migrations.AddField(
            model_name='scans',
            name='warns',
            field=models.CharField(blank=True, max_length=1400),
        ),
    ]
